name: core
description: A module for core functionality.

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  http: ^1.2.2

  # BloC State Management
  flutter_bloc: ^8.1.3

  # Json Annotation
  json_annotation: ^4.9.0

  # Handle Success/Error State From Data Source
  dartz: ^0.10.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_modular: ^5.0.3

  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  build_runner: ^2.4.11